name: CardGameEngine
version: '1.0-SNAPSHOT'
main: us.mudkip989.mods.cge.CGE
api-version: '1.21'
depend: [ ProtocolLib ]
commands:
  cge:
    usage: /<command>
    description: Empty Text.
    aliases: []
  games:
    usage: /<command> <game>
    description: Testing command.
    aliases: []
